### ISSUE TITLE
Is it possible to depend on express-useragent directly?

### ISSUE THREAD

**Issue by chinesedfan** [rvboris/koa-useragent#12]
Does this project add some special logic? Or just want to keep it independent?

**Comment by rvboris** [comment]
Hi, the first versions of the library worked completely copying the source module, but after switching to koa 2 I decided to completely rewrite the code in a class based form. I periodically update it after the source library. If there are any inconsistencies, you can create new issues.

**Comment by chinesedfan** [comment]
No inconsistencies. Can you explain benefits of "rewrite the code"? ES6 grammar?

In fact, we can reference express-useragent directly like following codes, instead of maintaining an ES6 version.

```
- const UserAgent = require('./lib/useragent');
+ const UserAgent = require('express-useragent').UserAgent;
```

**Comment by rvboris** [comment]
A few lines of code in months is not a big problem for maintain. It would be much more difficult to monitor critical changes in the source library.

Since this project is only for koa there is no need to support the client version, so why not rewrite to clean es6 code?

The project does not contain any dependencies, which is quite nice for developer.

**Comment by chinesedfan** [comment]
About the risk of breaking changes, we can lock versions of dependencies.

Of course, ES6 grammer is more readable and easier to maintain. And independence is a good feature.

Thanks for your reply. All of above is a kind of tradeoff. :)
