### ISSUE TITLE
Export `UserAgent` type into a developer realm

### ISSUE THREAD

**Issue by valerybugakov** [rvboris/koa-useragent#34]
It would be useful to have access to `UserAgent` type.

**Comment by rvboris** [comment]
Hello, check new version please 1b063338b2934f61e0257e4b4d08102c1c29c88f

**Comment by etc-tiago** [comment]
> Hello, check new version please [1b06333](https://github.com/rvboris/koa-useragent/commit/1b063338b2934f61e0257e4b4d08102c1c29c88f)

Hi, vscode show up this message: 

```
No overload matches this call.
  Overload 1 of 2, '(...middleware: Middleware<ParameterizedContext<any, IRouterParamContext<any, {}>>>[]): Router<any, {}>', gave the following error.
    Argument of type '(ctx: Koa.Context, next: Koa.Next) => Promise<any>' is not assignable to parameter of type 'Middleware<ParameterizedContext<any, IRouterParamContext<any, {}>>>'.
      Types of parameters 'ctx' and 'context' are incompatible.
        Property 'userAgent' is missing in type 'ExtendableContext & { state: any; } & IRouterParamContext<any, {}>' but required in type 'Context'.
  Overload 2 of 2, '(path: string | RegExp | string[], ...middleware: Middleware<ParameterizedContext<any, IRouterParamContext<any, {}>>>[]): Router<...>', gave the following error.
    Argument of type '(ctx: Koa.Context, next: Koa.Next) => Promise<any>' is not assignable to parameter of type 'string | RegExp | string[]'.
      Type '(ctx: Context, next: Next) => Promise<any>' is missing the following properties from type 'string[]': pop, push, concat, join, and 25 more.ts(2769)
index.d.ts(6, 9): 'userAgent' is declared here.
```

Seans useful export `UserAgent` type to extends the Context like:

```typescript
export const UserAgentContext extends Context {
   userAgent: UserAgent;
}
```

**Comment by valerybugakov** [comment]
@rvboris yeah, I was talking about the same thing – export of `UserAgent` type would be helpful.

**Comment by gbiryukov** [comment]
I agree with others, this module should not modify `koa` typings because it result in incorrect types.
Let me demonstare it:
```ts
const app = new Koa()
  .use(logUseragentMiddleware)
  .use(koaUseragent)
```
In this situation typescript would not complain but essentially `logUserAgentMiddleware` would not have access to `userAgent` context field until next middleware would be executed.

Instead `koa` has build-it mechanism for such cases, `.use` method is actually generic:
```ts
type TUserAgentContext = {
  userAgent: ...
};

const app = new Koa()
  .use<{}, TUserAgentContext>(koaUseragent)
  .use(logUseragentMiddleware)
```

First `.use()` call would ensure that `koaUseragent` will add required field to context and second `.use()` call would inherit updated context type.

So any middlewares used before `koaUseragent` would not have `userAgent` in context and TS will highlight if anything would try to access it.

How it sounds for you @rvboris?

**Comment by rvboris** [comment]
@gbiryukov Thanks for the explanation! I removed context modification and fix some typings and i add TS example in the readme for clarification. Check the latest version, please.

**Comment by gbiryukov** [comment]
Works great, thank you so much!
I believe this issue is resolved
